---
apiVersion: v1
kind: Service
metadata:
  name: flask-react-app-service
spec:
  selector:
    app: flask-react-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-react-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-react-app
  template:
    metadata:
      labels:
        app: flask-react-app
    spec:
      containers:
        - name: flask-react-app
          image: europe-west2-docker.pkg.dev/GOOGLE_PROJECT/react-flask-app-repo/app:latest
          ports:
            - containerPort: 5000
