apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-react-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-react-app
  template:
    metadata:
      labels:
        app: flask-react-app
    spec:
      containers:
        - name: flask-react-app
          image: gcr.io/python-api-challenge-401719/react-flask-app-repo:v1.0
          ports:
            - containerPort: 5000
