name: Build and Deploy React Flask App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Install the gcloud CLI
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          install_components: "gke-gcloud-auth-plugin"
          export_default_credentials: true

      - name: Build and push the docker image
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        run: |
          gcloud auth configure-docker europe-west2-docker.pkg.dev
          docker build -t europe-west2-docker.pkg.dev/$GOOGLE_PROJECT/react-flask-app-repo/app:latest .
          docker push europe-west2-docker.pkg.dev/$GOOGLE_PROJECT/react-flask-app-repo/app:latest

      - name: Deploy to GKE
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
          WORDS_API_KEY: ${{ secrets.WORDS_API_KEY }}
        run: |
          gcloud container clusters get-credentials gke-01-prod --region europe-west2 --project $GOOGLE_PROJECT
          sed -i -e "s/GOOGLE_PROJECT/$GOOGLE_PROJECT/g" -e "s/weather-api-key/$WEATHER_API_KEY/g" -e "s/words-api-key/$WORDS_API_KEY/g" resources.yaml
          kubectl apply -f resources.yaml

      - name: Remove local docker image
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        run: |
          docker rmi europe-west2-docker.pkg.dev/$GOOGLE_PROJECT/react-flask-app-repo/app:latest
